language: node_js
node_js:
  - "12.15"
install:
  - npm install
before_script:
  - echo about to run script
script:
  - npm run test
after_success:
  - npm run success
after_failure:
  - npm run makeCat
